import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {BrowserRouter,useNavigate} from "react-router-dom";
import "./styles.css";

const API=import.meta.env.VITE_API_URL||"http://localhost:4000";
async function api(path:string,opts:any={}){const token=localStorage.getItem("token");const r=await fetch(API+path,{...opts,headers:{"content-type":"application/json",...(token?{authorization:"Bearer "+token}:{}),...(opts.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d;}

function App(){
 const [page,setPage]=useState("home"); const [me,setMe]=useState<any>(null); const [err,setErr]=useState("");
 useEffect(()=>{if(localStorage.getItem("token"))api("/me").then(setMe).catch(()=>localStorage.removeItem("token"))},[]);
 if(!me) return <Auth onLogin={setMe} setErr={setErr} err={err}/>;
 return <div className="app"><header><b>🎨 ToonAI Studio</b><span>{me.credits} credits</span></header><main>{page==="home"?<Home setPage={setPage}/>:page==="create"?<Create me={me} onDone={()=>{api("/me").then(setMe);setPage("projects")}}/>:<Projects/>}</main><nav><button onClick={()=>setPage("home")}>Home</button><button onClick={()=>setPage("create")}>Create</button><button onClick={()=>setPage("projects")}>Projects</button><button onClick={()=>{localStorage.removeItem("token");location.reload()}}>Profile</button></nav></div>
}
function Auth({onLogin,setErr,err}:{onLogin:any,setErr:any,err:string}){const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [signup,setSignup]=useState(false);return <div className="auth"><h1>ToonAI Studio</h1><p>AI animation for Indian creators.</p><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password (8+ chars)" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={async()=>{try{const d=await api(signup?"/auth/signup":"/auth/login",{method:"POST",body:JSON.stringify({email,password})});localStorage.setItem("token",d.token);onLogin(await api("/me"))}catch(e:any){setErr(e.message)}}}>{signup?"Create account":"Login"}</button><button className="link" onClick={()=>setSignup(!signup)}>{signup?"Already have account? Login":"New user? Create account"}</button>{err&&<small>{err}</small>}</div>}
function Home({setPage}:any){return <><section className="hero"><h2>Create animated videos with AI</h2><p>Start with 10 free credits. No fake generation—configured AI providers are required.</p><button onClick={()=>setPage("create")}>Create Animation</button></section><div className="grid"><Card t="Image to Video"/><Card t="AI Story"/><Card t="AI Voice"/><Card t="Recent Projects" onClick={()=>setPage("projects")}/></div></>}
function Card({t,onClick}:{t:string,onClick?:any}){return <button className="card" onClick={onClick}>{t}<span>›</span></button>}
function Create({onDone}:{me:any,onDone:any}){const [form,setForm]=useState({title:"My Animation",prompt:"Ek superhero aasman mein ud raha hai aur futuristic city ko save kar raha hai.",durationSec:5,aspectRatio:"9:16",style:"2D Cartoon",camera:"Cinematic",quality:"Standard"});const [busy,setBusy]=useState(false);const go=async()=>{setBusy(true);try{await api("/projects/text-to-video",{method:"POST",body:JSON.stringify(form)});onDone()}catch(e:any){alert(e.message)}finally{setBusy(false)}};return <section><h2>Text to Animation</h2><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Prompt<textarea value={form.prompt} onChange={e=>setForm({...form,prompt:e.target.value})}/></label><div className="row"><select value={form.durationSec} onChange={e=>setForm({...form,durationSec:Number(e.target.value)})}>{[5,10,15,30].map(x=><option key={x}>{x}</option>)}</select><select value={form.aspectRatio} onChange={e=>setForm({...form,aspectRatio:e.target.value})}><option>9:16</option><option>16:9</option><option>1:1</option></select></div><select value={form.style} onChange={e=>setForm({...form,style:e.target.value})}>{["2D Cartoon","3D Cartoon","Anime-inspired","Kids","Cinematic","Fantasy","Comic","Storybook","Cute","Clay/Stop Motion"].map(x=><option key={x}>{x}</option>)}</select><select value={form.camera} onChange={e=>setForm({...form,camera:e.target.value})}>{["Static","Zoom","Pan","Tracking","Cinematic"].map(x=><option key={x}>{x}</option>)}</select><button disabled={busy} onClick={go}>{busy?"Starting…":"Generate Video"}</button></section>}
function Projects(){const [p,setP]=useState<any[]>([]);useEffect(()=>{api("/projects").then(setP).catch(()=>{})},[]);return <section><h2>Projects</h2>{p.length===0?<p>No projects yet.</p>:p.map(x=><div className="project" key={x.id}><b>{x.title}</b><span>{x.status}</span><small>{x.durationSec}s · {x.aspectRatio}</small></div>)}</section>}
createRoot(document.getElementById("root")!).render(<BrowserRouter><App/></BrowserRouter>);
